.travis.yml
LICENSE
package.json

See https://github.com/cargomedia/pulsar-rest-api or https://github.com/cargomedia/socket-redis
- license
- CI
- binary
- etc

Initial boilerplate

---

.gitignore
config/default.json
lib/cm-http-server.js
lib/http-server.js
lib/index.js
lib/janus-proxy.js
lib/logger.js
package.json

Authentication based on defined secret.
Actions:
- `/stopStream` (using clientKey/special identifier)
- `/status` (list existing streamchannels and their streams) - is it really needed?

Define HTTP server

---

lib/http-server.js
lib/janus-connection.js
lib/proxy-connection.js

How to model: Open `streamingtest.html` -> Watch any stream -> Click **Stop** button (see the picture).
@fvovan @tomaszdurka FYI

Detach of Streaming plugin during the actual streaming kills the proxy

---

lib/connection.js
lib/janus-proxy.js
lib/plugin/streaming.js
lib/proxy-connection.js
lib/stream.js
lib/streams.js

Cannot find method `processMessage` of undefined which in this case should be `Plugin`. Plugin is accesed via `return this.getPlugin(pluginId).processMessage(message);`
Log:
```
app debug <- janus { janus: 'hangup',
session_id: 3280711602,
sender: 2864469971,
reason: 'DTLS alert' }
app error [TypeError: Cannot read property 'processMessage' of undefined] TypeError: Cannot read property 'processMessage' of undefined
at ProxyConnection.processMessage (/Users/tomasz/projects/cargomedia/cm-janus/lib/proxy-connection.js:27:36)
at JanusConnection.<anonymous> (/Users/tomasz/projects/cargomedia/cm-janus/lib/janus-proxy.js:42:23)
at JanusConnection.emit (events.js:107:17)
at JanusConnection.Connection._onMessage (/Users/tomasz/projects/cargomedia/cm-janus/lib/connection.js:78:10)
at …
```

Plugin not found

---

lib/browser-connection.js
lib/errors.js
lib/janus-error.js
lib/plugin/streaming.js
lib/proxy-connection.js

For example.
-------------------------------------------------
```json
{
"janus" : "error",
"transaction" : "--------"
"error" : {
"code" : 405
"reason" : "Illegal plugin to access"
}
}
```
- ProxyConnection.onAttach:
```js
if (!this.isAllowedPlugin(message.plugin)) {
return Promise.reject('Disallowed plugin ' + message.plugin);
}
```
- ProxyConnection.pluginFactory:
```js
if (!pluginClass) {
throw new Error('Invalid plugin');
}
```
----------------------------------------------------------------------------------
```json
{
"janus" : "error",
"transaction" : "--------"
"error" : {
"code" : 403
"reason" : "Unauthorized request"
}
}
```
- BrowserConnection._onMessage:
```js
auth.authorizeConnection(this, token)
```
- BrowserConnection._send:
```js
auth.isValidConnection(this)
```
- …

Feedback of unexpected/error cases.

---

bin/cm-janus
bin/config.yaml
lib/cm-api-client.js
lib/config.js
lib/http-server.js

Rename apiKey to serverKey

---

README.md
bin/cm-janus
bin/config.yaml
lib/cm-api-client.js
lib/config.js
lib/http-server.js

Move proxy details to config and create split API keys for http-server  and cm-api-client

Adjust config and split api keys.

---

.travis.yml
README.md

Add travis build

---

lib/auth.js
lib/cm-api-client.js
package.json
test/mocha.opts
test/unit/auth.js

Introduce testing frameworks

---

bin/config.yaml
lib/config.js
lib/index.js
lib/logger.js

Possibly try to wrap existing code with new created class and delegate all used methods to minilog.

make Logger to be a class

---

.travis.yml

Update node version in Travis config

---

lib/plugin/plugin-registry.js
lib/plugin/streaming.js
lib/proxy-connection.js
test/spec/proxy-connection.js
test/unit/plugin-registry.js

Move pluginFactory out of ProxyConnection

---

lib/cm-api-client.js
lib/plugin/streaming.js
lib/plugin/video.js
test/spec/cm-api-client.js
test/unit/cm-api-client.js
test/unit/plugin-streaming.js
test/unit/plugin-video.js

Expect additional data-bag for plugin events like:
- Video::onCreate
- Audio::onCreate (not there yet)
This should be sent by client using `message['data']`

Expect additional data-bag

---

lib/plugin/streaming.js

Datetime is passed in miliseconds in create/webrtcup event

---

lib/janus/plugin/abstract.js
lib/janus/plugin/audio.js
lib/janus/plugin/streaming.js
lib/janus/plugin/video.js
test/spec/janus/plugin/audio.js
test/spec/janus/plugin/video.js

Allow for all:
- create 
- join (detach if not able to subscribe)
- changeroom (detach if not able to subscribe)
- configure
- leave
Deny for all:
- exists
- resetdecoder
- listparticipants
- destroy
- list

Introduce acl for audio plugin

---

lib/cm-api-client.js
test/spec/cm-api-client.js
test/unit/cm-api-client.js

Related to https://github.com/cargomedia/cm/pull/2039

Upgrade rpc endpoints to CM 1.164.0

---

README.md
bin/config.yaml
lib/cm-application.js
lib/index.js
lib/job/handler.js
lib/job/manager.js
lib/job/model/abstract.js
lib/job/model/audioroom-recording.js
lib/job/model/rtpbroadcast-recording.js
lib/job/model/rtpbroadcast-thumbnail.js
test/spec/job-manager.js
test/spec/job/model/abstract.js
test/spec/job/model/audioroom-recording.js
test/spec/job/model/rtpbroadcast-recording.js
test/spec/job/model/rtpbroadcast-thumbnail.js
test/unit/cm-application.js
test/unit/job/handler-registry.js

Streamline job handling (logging, cleaning, etc)

---

README.md

@vogdb @tomaszdurka 
- How to install dependencies
- How to run tests
- How to release
- Travis will release to npm automatically?
- How to create the tag? Needs to be created *before* the travis build?

Add "development" docu

---

lib/job/model/abstract.js
package.json
test/helpers/test-jobs.js
test/spec/job/model/abstract.js
test/spec/job/model/audioroom-recording.js
test/spec/job/model/rtpbroadcast-recording.js
test/spec/job/model/rtpbroadcast-thumbnail.js

```
2016-01-22 14:35:18.235 ERROR - Error: stderr maxBuffer exceeded.
at Socket.<anonymous> (child_process.js:806:12)
at Socket.emit (events.js:107:17)
at readableAddChunk (_stream_readable.js:163:16)
at Socket.Readable.push (_stream_readable.js:126:10)
at Pipe.onread (net.js:540:20)
```
@tomaszdurka @vogdb will this abort the job? if so, then let's find a way to handle it more gracefully.

Job handler: Error: stderr maxBuffer exceeded.

---

package.json

- Unhandled rejection (#193, @vogdb)
- Remove failed jobs working directories (#200, @tomaszdurka)
- Re-add failed jobs after 1 minute (#199, @tomaszdurka)
- Allow to run cm-janus with specific modules only (#198, @tomaszdurka)
- Fails to start if cm can't be reached (#201, @tomaszdurka)

Release 0.6.3

---

package.json

- Remove stream even after failed detach (#195, @vogdb)
- Cannot write to buffer - blocks process from running (#206, @vogdb)
- Add error information to  "Failed job process" exceptions (#205, @vogdb)
- Use NestedError instead of concatenating error.stack with wrapper message (#207, @vogdb)

Release 0.6.4

---

package.json

- Add fluentd to VM (#210, @njam)
- Add Config specs (#214, @vogdb)
- Log JSON (#213, @vogdb)
- Change file log formatting to JSON (#218, @tomaszdurka)

Release 0.6.5

---

README.md

@tomaszdurka @vogdb add some comments / maybe curl example?

Readme: Add docu about status HTTP endpoint

---

lib/janus/connection.js
lib/janus/plugin/abstract.js
lib/janus/plugin/audio.js
lib/janus/plugin/video.js
lib/janus/proxy.js
lib/janus/session.js
test/spec/janus/plugin/abstract.js
test/spec/janus/session.js

```js
Connection.prototype.serialize = function() {
return {connection: this.id};
};
Session.prototype.serialize = function() {
return _.extend(this.connection.serialize(), {session: this.id});
};
PluginAbstract.prototype.serialize = function() {
return _.extend(this.session.serialize(), {plugin: this.id});
};
```

Use serialize concept to get logger fields

---

package.json

Release 0.6.8

---

lib/global/error.js

https://github.com/cargomedia/guides/tree/master/logging

Adjust Error toJSON according to Logging guide

---

lib/channel.js
lib/cm-api-client.js
lib/cm-application.js
lib/context.js
lib/global/log4js-layout-json.js
lib/http-server.js
lib/index.js
lib/janus/connection.js
lib/janus/http-client.js
lib/janus/plugin/abstract.js
lib/janus/plugin/streaming.js
lib/janus/proxy.js
lib/janus/session.js
lib/job/manager.js
lib/job/model/abstract.js
lib/job/model/audioroom-recording.js
lib/job/model/rtpbroadcast-recording.js
lib/job/model/rtpbroadcast-thumbnail.js
lib/job/processor.js
lib/stream.js
package.json
test/spec/janus/connection.js

See https://github.com/cargomedia/guides/tree/master/logging

Change logging schema to comply with cargomedia standard

---

lib/context.js

message: Unexpected rejection error.
error.stack:
```
Error: cm-api error: Unexpected response format
at /usr/lib/node_modules/cm-janus/lib/cm-api-client.js:62:15
at tryCatcher (/usr/lib/node_modules/cm-janus/node_modules/request-promise/node_modules/bluebird/js/main/util.js:26:23)
at Promise._settlePromiseFromHandler (/usr/lib/node_modules/cm-janus/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:507:31)
at Promise._settlePromiseAt (/usr/lib/node_modules/cm-janus/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:581:18)
at Promise._settlePromises (/usr/lib/node_modules/cm-janus/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:697:14)
at Async._drainQueue (/usr/lib/node_modules/cm-janus/node_modules/request-promise/node_modules/ …
```

Fatal error: cm-api error: Unexpected response format

---

package.json

https://cargomedia.loggly.com/search/?terms=tag%3Acm-janus+AND+json.level%3Afatal&source_group=&savedsearchid=206843&from=2016-04-26T19%3A37%3A28Z&until=2016-04-26T19%3A42%3A28Z
```
{"level":"fatal","message":"Unexpected rejection error.","exception":{"type":"Error","message":"zlib binding closed","stack":"Error: zlib binding closed
at DeflateRaw.Zlib._transform (zlib.js:493:15)
at DeflateRaw.Transform._read (_stream_transform.js:167:10)
at DeflateRaw.Transform._write (_stream_transform.js:155:12)
at doWrite (_stream_writable.js:300:12)
at clearBuffer (_stream_writable.js:407:7)
at onwrite (_stream_writable.js:339:7)
at WritableState.onwrite (_stream_writable.js:89:5)
at afterTransform (_stream_transform.js:79:3)
at TransformState.afterTransform (_stream_transform.js:54:12)
at …
```

Loggly Alert: cm-janus fatal error

---

package.json

- Loggly Alert: cm-janus fatal error (#256, @vogdb)

Release 0.8.3

---

codecov.yaml

Recently Codecov changed its configuration approach. We need to add its conf file.

Add codecov conf

---

lib/cm-api-client.js

https://cargomedia.loggly.com/search/?terms=LogglyNotifications.type%3AMappingConflict&from=-1d&until=now&source_group=&savedsearchid=208919&newtab=true&tabname=loggly%20MappingConflicts&savedsearchid=208919&isfav=False&searchorder=desc
@vogdb can you investigate?
cc @tomaszdurka 
See also https://github.com/cargomedia/cm-janus/issues/231

Loggly: MappingConflict

---

lib/job/model/abstract.js
package.json

Which would be true or false.
So we can search for it in Loggly.
cc @tomaszdurka

Replace job failure's "retryCount" with "failedRepeatedly"

---

lib/context.js
package.json

It does not extend Error objects
unclechu/node-deep-extend#26

drop deep-extend dependency

---

lib/http-server.js
lib/janus/plugin/streaming.js
lib/janus/proxy.js
lib/streams.js
package.json
test/spec/http-server.js
test/spec/janus/plugin/streaming.js
test/spec/janus/proxy.js
test/unit/streams.js

https://cargomedia.loggly.com/search/?terms=tag%3Acm-janus+AND+json.level%3Afatal&source_group=&savedsearchid=206843&from=2016-08-19T13%3A06%3A19Z&until=2016-08-19T13%3A11%3A19Z
```
{"level":"fatal","message":"Stream stop failed. Stream was not removed.","janus":{"streamId":"7026ba9d-1906-4ffa-bb7a-d1f424ada0e5","channelId":"08af6604c641b8445b3ee98e950c5472","channelKey":"qudFENTdDvB.gV93solawQ__","pluginId":3315138749,"sessionId":2734977818,"connectionId":"9f9a0d73-89db-48d5-a184-1ac3ece60f94"},"FB":{"client":"158578630","browserWindow":"f820122c-0d5f-4cfa-9606-d282e69503c1","user":15999310},"exception":{"type":"Error","message":"cm-api error: 500 - {"success":{"result":false},"deployVersion":1471610862}Internal server error
","stack":"
Error: cm-api error: 500 - …
```

CM Api request errors should not be logged as fatals
