cargomedia/cm-janus

lib/cm-api-client.js
lib/http-server.js

- Consider using the same `apiKey` for `HttpServer` and `CMApiClient`
- Use header for `HttpServer` `apiKey` authentication
- Send `apiKey` as first param in all `CMApiClient` `requests`
Example
```js
{
method: 'CM_Janus_RpcEndpoints.publish',
params: ['apiKey', 'streamKey', '...']
}
```
For other signatures check https://github.com/tomaszdurka/CM/blob/issue-1965/library/CM/Janus/RpcEndpoints.php

Add token/secret to HttpServer handlers and CMApiClient requests

---

lib/http-server.js
lib/janus-proxy.js
lib/plugin/streaming.js
lib/stream.js

We need to know what actually stream represents (publish or subscribe). It is required for syncing, where we delete inconsistent data on CM part (non deleted for some reasons publisher streams, absent publishers streams for existing subscribers e t.c.)

Add 'isPublish' attribute to Stream.

---

lib/cm-api-client.js
lib/index.js
lib/logger.js

Allow to create instances of and mock Logger class.
Service registry:
```js
var Logger = require('./logger');
var serviceLocator = require('./service-locator');
serviceLocator.register('logger', function() {
var logger = new Logger();
var logFilePath = __dirname + '/../' + this.config['logPath']
var stream = fs.createWriteStream(logFilePath, {flags: 'a', defaultEncoding: 'utf8'});
logger.pipe(stream);
return logger;
});
```
Not sure if it's possible with minilog which signature is quite strange (unless you know different way than we use).

Make Logger more oop

---

lib/index.js

After having tried to run as a non-root user I found out that the log location needs be in a place where the app user has rights to write to
Ideally, this is configurable. A common place where log files are stored in our setup is `/var/log/<appname>`
As-of-now, this is only possible by prefixing the path with as many `../` as the depth of where the app is installed, e.g. `logPath: '../../../../../../../../home/vagrant/app.log'` because of https://github.com/cargomedia/cm-janus/blob/master/lib/index.js#L19

Allow to use arbitrary paths for log

---

test/helpers/global-error-handler.js
test/spec/cm-api-client.js
test/spec/job-manager.js
test/unit/auth.js
test/unit/cm-api-client.js
test/unit/connection.js
test/unit/service-locator.js

Currently if an error is thrown inside a promise without `catch` block, we loose it and tests exit by timeout.

Global error handler in tests

---

lib/plugin/streaming.js

@tomaszdurka @vogdb @fvovan 
```
Unhandled rejection TypeError: Cannot read property 'close' of undefined
at /usr/lib/node_modules/cm-janus/lib/plugin/streaming.js:53:33
at tryCatcher (/usr/lib/node_modules/cm-janus/node_modules/request-promise/node_modules/bluebird/js/main/util.js:26:23)
at Promise._settlePromiseFromHandler (/usr/lib/node_modules/cm-janus/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:507:31)
at Promise._settlePromiseAt (/usr/lib/node_modules/cm-janus/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:581:18)
at Promise._settlePromises (/usr/lib/node_modules/cm-janus/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:697:14)
at Async._drainQueue (/usr/lib/node_modules/cm-janus/node_modules/request-promise/node_m …
```

streaming: close of undefined

---

lib/connection.js
package.json
test/helpers/websocket.js

My test shows that if websocket connection is closed between any `client` (studio-agent) and the `cm-janus` then the connection between `cm-janus` and `janus` is still alive?
could you verify?

Fix: properly cleanup websocket connection between cm-janus and janus

---

lib/plugin/streaming.js

Should use `message['body']['channel_data']` instead of `message['channelData']`.

Fix chanelData read in streaming pluign

---

lib/cm-api-client.js
test/unit/cm-api-client.js

When an RPC call to the CM application fails, the application responds with a JSON structure of this form:
```json
{"type": "CM_Exception_AuthRequired", "msg": "Internal Server Error", "isPublic": false}
```
Afaik cm-janus currently only displays the `msg`. Logging additionally the `type` would be handy.
@tomaszdurka @fvovan @vogdb wdyt?

RPC Error logging

---

lib/janus/plugin/streaming.js
package.json
test/spec/cm-api-client.js
test/spec/janus/plugin/streaming.js

During testing we experienced that while the `publish()` and `subscribe()` endpoints are called it seems like `rpc_removeStream()` is not!
Could reproduce this when closing WebSocket connection to cm-janus.
@tomaszdurka can you look into this and/or reassign?

rpc_removeStream never called

---

lib/janus/plugin/streaming.js
lib/janus/plugin/video.js
test/spec/janus/plugin/video.js

https://github.com/cargomedia/sk/blob/master/library/VR/client-vendor/after-body-source/vr/janus/plugin/video.js
Intercept `switch` event:
- remove previous stream (and store new one) on incoming client message
- subscribe new stream on janus response

Support switch event for video plugin

---

lib/janus/error.js
lib/janus/plugin/streaming.js
test/spec/janus/plugin/streaming.js

The vendor janus client [only call `onmessage` when the `transaction` id is set](https://github.com/cargomedia/sk/blob/master/library/VR/client-vendor/after-body/04-janus/janus.js#L326), but cm-janus specific error have no reference to a transaction, for example:
```
{"janus":"error","error":{"code":490,"reason":"Cannot subscribe: Stream{\"id\":\"049626f1-7909-4e52-af74-d60c00f41e95\"} error: cm-api error: CM_Exception_NotAllowed. Internal server error"}}
{"janus":"error","transaction":"9KuoI217vK2O","error":{"code":490,"reason":"Invalid plugin"}}
```
2 solutions:
- cm-janus send a valid message, with the transaction id
- change the vendor client source code to call the `janus.error` callback if there's no transaction id
related to cargomedia/sk#2507
@njam fyi

Error message should refer to a transaction

---

lib/janus/connection.js
test/spec/janus/connection.js

@tomaszdurka @vogdb 
Example message from janus:
```
app debug <- janus {"janus":"timeout","session_id":1610821549}
```

Destroy session on "timeout"

---

lib/channels.js
lib/janus/plugin/audio.js

We have added support for transparent `audioroom` creation if `room` does not exist on `join/changeroom` request. It is done here https://github.com/cargomedia/janus-gateway-audioroom/pull/27 and support for
> 
- Rooms should created transparently. If a room doesn't exist on "join" and "changeroom" it would be created
- There should be no more "master" connection - i.e. the room is not destroyed when the "master" disconnects
- When the last user leaves the room it is destroyed.
@tomaszdurka @vogdb we get this error currently
```
app debug <- janus {"janus":"event","session_id":1889884226,"sender":1787354233,"transaction":"Cc2AXggJAZ24","plugindata":{"plugin":"janus.plugin.cm.audioroom","data":{"audioroom":"joined","id":"nNOeUH4Q6aIvVjdTfYexlQ__","userid":397326083,"participants":[{"userid" …
```

Add support for transparent "audioroom" create on join/changeroom

---

lib/janus/plugin/audio.js
test/spec/janus/plugin/audio.js

@tomaszdurka @vogdb @njam 
We should make sure that `cm-janus` is aware of room destroy event. If room is destroyed of any reason e.g. master session expires then Janus removes room and notify all connected sessions to the audioroom plugin. It sends something like this:
```
{
"janus": "event",
"session_id": 1389549831,
"sender": 2462998037,
"plugindata": {
"plugin": "janus.plugin.cm.audioroom",
"data": {
"audioroom": "destroyed",
"id": "1234"
}
}
}
``` 
We should make sure to remove `stream` in `CM` then with e.g. `rpc_removeStream`?
@tomaszdurka can you confirm it is implemented?

Verify if cleanup is done when "audioroom" is destroyed

---

lib/janus/plugin/video.js
test/spec/janus/plugin/video.js

@tomaszdurka @vogdb @njam
We should make sure that `cm-janus` is aware of `mountpoint` destroy event. If `mountpoint` is destroyed of any reason e.g. master session expires then Janus removes `mountpoint` and notify all connected sessions to the `rtpbroadcast` plugin. It sends following messages:
```
{
"janus": "event",
"session_id": 1734302109,
"sender": 2805623492,
"plugindata": {
"plugin": "janus.plugin.cm.rtpbroadcast",
"data": {
"streaming": "event",
"result": {
"status": "stopped"
}
}
}
}
```
and
```
{
"janus": "hangup",
"session_id": 1734302109,
"sender": 2805623492,
"reason": "DTLS alert"
}
```
We should make sure to remove `stream` in `CM` then with e.g. `rpc_removeStream`?
@tomaszdurka can you confirm it is implemented?

Verify if cleanup is done when "mountpoint" is destroyed

---

README.md
bin/config.yaml

- add handlers to docu
- adjust default config to use correct mjr2webm notation (swap audio/video arguments to: `mjr2webm <%= videoMjrFile %> <%= audioMjrFile %> <%= webmFile %>`)

Adjust configuration information about handlers

---

lib/janus/connection.js

```
app debug <- janus {"janus":"timeout","session_id":229926117}
app error TypeError: Cannot read property 'onRemove' of null
at JanusConnection._removeSession (/usr/lib/node_modules/cm-janus/lib/janus/connection.js:113:15)
at JanusConnection.onTimeout (/usr/lib/node_modules/cm-janus/lib/janus/connection.js:101:8)
at JanusConnection.processMessage (/usr/lib/node_modules/cm-janus/lib/janus/connection.js:48:17)
at Connection.<anonymous> (/usr/lib/node_modules/cm-janus/lib/janus/proxy.js:75:16)
at Connection.emit (events.js:107:17)
at Connection._onMessage (/usr/lib/node_modules/cm-janus/lib/connection.js:97:10)
at Connection.<anonymous> (/usr/lib/node_modules/cm-janus/lib/connection.js:21:10)
at WebSocket.emit (events.js:110:17)
at Receiver.ontext …
```

Timeout issue: Cannot read property 'onRemove' of null

---

lib/cm-api-client.js

```
app error Error: cm-api error: 500 - <h1>Exception</h1><h2>test</h2><pre>/home/vagrant/sk/vendor/cargomedia/cm/library/CM/Janus/RpcEndpoints.php on line 69</pre><pre>    0. {main} /home/vagrant/sk/public/index.php:0
1. CM_Http_Handler->processRequest(CM_Http_Request_Post) /home/vagrant/sk/public/index.php:8
2. CM_Http_Response_Abstract->process() /home/vagrant/sk/vendor/cargomedia/cm/library/CM/Http/Handler.php:26
3. CM_Http_Response_RPC->_process() /home/vagrant/sk/vendor/cargomedia/cm/library/CM/Http/Response/Abstract.php:47
4. CM_Http_Response_Abstract->_runWithCatching(Closure, Closure) /home/vagrant/sk/vendor/cargomedia/cm/library/CM/Http/Response/RPC.php:21
5. CM_Http_Response_RPC->{closure}() /home/vagrant/sk/vendor/cargomedia/cm/library/CM/Http/Response/Abstract.php:257
6. …
```

Failing RPC call closes connection?

---

lib/janus/plugin/streaming.js

```
app info cm-api request https://alicex.dev.cargomedia.ch/rpc/null {"method":"CM_Janus_RpcEndpoints.publish","params":["mad-panda","{\"sessionId\":\"79d6efc145f1cc79e2d1593b0b6f6c07\"}","WjexdytNPTosH5VkDiq17A__","7b251c823714820365ade577b077674e","{\"streamChannelType\":269}","2c03a7ed-a315-4059-9073-793e8e633547",1453139254.06]}
app info cm-api response 
app info cm-api response 
app debug <- janus {"janus":"webrtcup","session_id":3089257324,"sender":234971487}
app error TypeError: Cannot read property 'plugin' of null
at CMApiClient.subscribe (/usr/lib/node_modules/cm-janus/lib/cm-api-client.js:75:11)
at PluginAudio.PluginStreaming.subscribe (/usr/lib/node_modules/cm-janus/lib/janus/plugin/streaming.js:32:46)
at PluginAudio.PluginStreaming.processMessage …
```

subscribe: Cannot read property 'plugin' of null

---

lib/cm-application.js
lib/job/model/rtpbroadcast-thumbnail.js
test/spec/job/model/rtpbroadcast-thumbnail.js
test/unit/cm-application.js

New field "createdAt" (unix timestamp) was added to thumbnail job descriptions:
https://github.com/cargomedia/janus-gateway-rtpbroadcast/pull/57
It will be expected as a new third argument to `importVideoThumbnail` in https://github.com/cargomedia/cm/pull/2065
@tomaszdurka @vogdb can you pass it along accordingly?
Can you check if it's okay to pass superfluous arguments to the CLI call - so that we could merge this here first, and then change it in CM.

Pass along thumbnail "createdAt" to cm

---

lib/connection.js
lib/janus/proxy.js
test/spec/janus/proxy.js

```
app error Unexpected rejection error. Error: write after end
at writeAfterEnd (_stream_writable.js:167:12)
at Socket.Writable.write (_stream_writable.js:214:5)
at Socket.write (net.js:636:40)
at Sender.frameAndSend (/usr/lib/node_modules/cm-janus/node_modules/ws/lib/Sender.js:224:22)
at /usr/lib/node_modules/cm-janus/node_modules/ws/lib/Sender.js:126:12
at /usr/lib/node_modules/cm-janus/node_modules/ws/lib/PerMessageDeflate.js:290:5
at afterWrite (_stream_writable.js:361:3)
at onwrite (_stream_writable.js:352:7)
at WritableState.onwrite (_stream_writable.js:105:5)
at afterTransform (_stream_transform.js:99:5)
at TransformState.afterTransform (_stream_transform.js:74:12)
at Zlib.callback (zlib.js:611:5)
```

Do not treat web-socket write exceptions as errors

---

lib/janus/connection.js
lib/janus/error.js
lib/janus/plugin/streaming.js
lib/janus/proxy.js
lib/janus/session.js

Transaction should be only added in proxy error handler (on top of the stack). We currently are not able to pass valid transaction from methods we still want to throw `Janus` errors.

Remove transaction field from JanusError

---

lib/janus/connection.js
lib/janus/plugin/abstract.js
lib/janus/plugin/streaming.js
lib/janus/proxy.js
lib/janus/session.js
test/spec/janus/connection.js
test/spec/janus/plugin/audio.js
test/spec/janus/plugin/streaming.js
test/spec/janus/session.js

As discussed keep `onRemove` and `_remove*` methods. Promisify them.

Make removing of connections, sessions, plugins promise-based

---

lib/job/model/abstract.js
test/spec/job/model/abstract.js

Currently I'm investigating a job conversion that's running for 9 days now (!). The file is 103GB, but still this is too long.
@tomaszdurka @vogdb should we add a timeout?
cc @kris-lab

Add timeout for job processing

---

lib/janus/connection.js
test/spec/janus/connection.js

I just experienced the mountpoint data of cm-janus going out of sync with janus' data.
cm-janus would still have the mountpoint, but janus doesn't have it anymore.
Mountpoint id: `kwLMiDIDdpKXBQ62IMDOQg__`
Log: https://gist.github.com/njam/fa5644aaf8b041b9e3fe
This is cm-janus 0.5.0. I understand it shouldn't happen with this version.
@tomaszdurka @vogdb could you investigate?

Multiple session support

---

lib/job/processor.js

Before we decided to keep failed jobs WD to investigate, not relevant for now.

Remove failed jobs working directories

---

README.md
bin/cm-janus
lib/http-server.js
lib/index.js

Allow to pass command-line option to run only specific modules, example usages:
```
cm-janus -c <config-file>
cm-janus -c <config-file> --server
cm-janus -c <config-file> --job-manager
cm-janus -c <config-file> --roles=server,job-manager
```

Allow to run cm-janus with specific modules only

---

lib/janus/proxy.js

When booting cm virtual machine:
cc @kris-lab @njam 
```
app debug WebSocket server on port 8210 started
app debug HTTP server on port 8100 started
app info Closing application
app debug WebSocket server on port 8210 started
app debug HTTP server on port 8100 started
app info Closing application
2016-03-07 11:22:45.294 INFO - cm-api request https://example.dev.cargomedia.ch/rpc/null { method: 'CM_Janus_RpcEndpoints.removeAllStreams',
params: [ 'mad-panda' ] }
2016-03-07 11:22:45.332 DEBUG - HTTP server on port 8100 started
2016-03-07 11:22:49.534 ERROR - Process failed. Exiting. Error: cm-api error: 500 - <h1>CM_Db_Exception</h1><h2>Database connection failed: SQLSTATE[42000] [1049] Unknown database 'sk'</h2><pre>/home/vagrant/sk/vendor/cargomedia/cm/library/CM/Db/Client.php on line …
```

Fails to start if cm can't be reached

---

lib/http-server.js
test/spec/http-server.js

Currently we remove stream by detaching plugin with http call.
We should catch http-call error and remove stream from local storage anyway.
Example error:
```
2016-03-02 05:59:53.164 DEBUG - request /stopStream
2016-03-02 05:59:53.164 INFO - http-client request http://localhost:8300/janus/3502223475/1258294074 { janus: 'detach', transaction: 'vzk5cgx6sv' }
2016-03-02 05:59:53.166 INFO - http-client response { janus: 'error',
session_id: 3502223475,
transaction: 'vzk5cgx6sv',
error: { code: 458, reason: 'No such session 3502223475' } }
2016-03-02 05:59:53.166 WARN - Stream stop failed [Error: http-client error: No such session 3502223475]
```

Remove stream even after failed detach

---

lib/job/model/abstract.js

As investigated: looks like lame is exhausting node.js' STDERR buffer?
```
$ strace -p 12542
Process 12542 attached - interrupt to quit
write(2, "\33[A\33[A\33[A", 9
```

Cannot write to buffer - blocks process from running

---

lib/job/model/abstract.js
package.json

Currently we get something like:
```
Error: Failed job process: `<command>`
at /usr/lib/node_modules/cm-janus/lib/job/model/abstract.js:127:13
at _rejected (/usr/lib/node_modules/cm-janus/node_modules/child-process-promise/node_modules/q/q.js:844:24)
at /usr/lib/node_modules/cm-janus/node_modules/child-process-promise/node_modules/q/q.js:870:30
at Promise.when (/usr/lib/node_modules/cm-janus/node_modules/child-process-promise/node_modules/q/q.js:1122:31)
at Promise.promise.promiseDispatch (/usr/lib/node_modules/cm-janus/node_modules/child-process-promise/node_modules/q/q.js:788:41)
at /usr/lib/node_modules/cm-janus/node_modules/child-process-promise/node_modules/q/q.js:604:44
at runSingle (/usr/lib/node_modules/cm-janus/node_modules/child-process-promise/node_modules/q/q.js:137:13)
at …
```

Add error information to  "Failed job process" exceptions

---

lib/index.js
lib/job/manager.js

Regarding this code:
```js
Promise.map(services, function(service) {
return service.start();
}).catch(function(error) {
serviceLocator.get('logger').error('Process failed. Exiting. ' + error.stack || error.message);
process.emit('close');
});
process.on('unhandledRejection', function(reason) {
serviceLocator.get('logger').error('Unexpected rejection error. ' + reason.stack || reason.message);
});
process.on('uncaughtException', function(err) {
serviceLocator.get('logger').error('Unexpected runtime error. Shutdown the process ' + err.stack || err.message);
process.emit('close');
});
```

Use NestedError instead of concatenating error.stack with wrapper message

---

lib/cm-api-client.js
test/unit/cm-api-client.js

Update from @vogdb. Depends on #225.
We've just experienced lots of calls to `rpc_removeStream()` in CM failing ([details](https://github.com/cargomedia/cm/issues/2115)).
I noticed that there were no errors logged in cm-janus about it.
Here's an example "removeStream":
https://cargomedia.loggly.com/search/?terms=&from=2016-04-02T15%3A54%3A03.407Z&until=2016-04-02T16%3A04%3A03.407Z&source_group=
I guess the next record is the response:
```json
{"level":"INFO","message":"cm-api","additionalMessages":["response",null]}
```
@tomaszdurka @vogdb can you check if we log API call errors correctly?

Errors from "CMApiClient.removeStream()" are not logged

---

lib/janus/proxy.js
lib/job/manager.js
lib/job/model/abstract.js
lib/job/model/audioroom-recording.js
lib/job/model/rtpbroadcast-recording.js
lib/job/model/rtpbroadcast-thumbnail.js
lib/job/processor.js

Whenever something bad/unexpected happens it should be "warning" or "error".
E.g. this should be "warning":
```
{"level":"info","error":{"code":1,"message":"`ionice -c 2 -n 7 nice
```
cc @tomaszdurka

Change some "info" log records to "warning" or "error"

---

lib/janus/plugin/streaming.js
test/spec/janus/plugin/streaming.js

```
json:
timestamp: 2016-04-06T12:27:54+00:00
message: Unexpected rejection error.
hostname: janus2.fuckbook.com
level: error
error:
message: http-client error: No such session 1942071661
stack:
Error: http-client error: No such session 1942071661
at /usr/lib/node_modules/cm-janus/lib/janus/http-client.js:36:15
at tryCatcher (/usr/lib/node_modules/cm-janus/node_modules/request-promise/node_modules/bluebird/js/main/util.js:26:23)
at Promise._settlePromiseFromHandler (/usr/lib/node_modules/cm-janus/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:507:31)
at Promise._settlePromiseAt (/usr/lib/node_modules/cm-janus/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:581:18)
at Promise._settlePromises …
```

Fix HttpClient.detach usages

---

lib/cm-api-client.js
lib/connection.js
lib/http-server.js
lib/index.js
lib/janus/connection.js
lib/janus/http-client.js
lib/janus/proxy.js
lib/job/manager.js
lib/job/model/abstract.js

Currently 50'000 events per hour => ~14 events per second.
Ideas:
- Combine debug records for the same transaction over some time? (instead of "-> browser", "-> janus" etc all separate?)
- What else?

Reduce number of (debug) log events

---

lib/cm-api-client.js
test/unit/cm-api-client.js

I guess this should not happen?
```
TypeError: Cannot read property 'error' of undefined
at /usr/lib/node_modules/cm-janus/lib/cm-api-client.js:50:27
at tryCatcher (/usr/lib/node_modules/cm-janus/node_modules/request-promise/node_modules/bluebird/js/main/util.js:26:23)
at Promise._settlePromiseFromHandler (/usr/lib/node_modules/cm-janus/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:507:31)
at Promise._settlePromiseAt (/usr/lib/node_modules/cm-janus/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:581:18)
at Promise._settlePromises (/usr/lib/node_modules/cm-janus/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:697:14)
at Async._drainQueue (/usr/lib/node_modules/cm-janus/node_modules/request-promise/node_modules/bluebird/js/m …
```

Cannot read property 'error' of undefined

---

lib/index.js
lib/janus/proxy.js

https://cargomedia.loggly.com/search/?terms=tag%3Acm-janus+AND+json.level%3Afatal&source_group=&savedsearchid=206843&from=2016-04-27T13%3A49%3A38Z&until=2016-04-27T13%3A54%3A38Z
```
{"level":"fatal","message":"Unexpected rejection error.","exception":{"type":"Error","message":"This socket has been ended by the other party","stack":"Error: This socket has been ended by the other party
at Socket.writeAfterFIN [as write] (net.js:284:12)
at Sender.frameAndSend (/usr/lib/node_modules/cm-janus/node_modules/ws/lib/Sender.js:232:22)
at /usr/lib/node_modules/cm-janus/node_modules/ws/lib/Sender.js:126:12
at /usr/lib/node_modules/cm-janus/node_modules/ws/lib/PerMessageDeflate.js:313:5
at afterWrite (_stream_writable.js:354:3)
at onwrite (_stream_writable.js:345:7)
at WritableState.onwrite …
```

Loggly Alert: cm-janus fatal error

---

lib/janus/proxy.js
package.json

https://cargomedia.loggly.com/search/?terms=tag%3Acm-janus+AND+json.level%3Afatal&source_group=&savedsearchid=206843&from=2016-05-04T19%3A14%3A54Z&until=2016-05-04T19%3A19%3A54Z
```
{"level":"fatal","message":"Unexpected rejection error.","exception":{"type":"Error","message":"This socket has been ended by the other party","stack":"Error: This socket has been ended by the other party
at Socket.writeAfterFIN [as write] (net.js:284:12)
at Sender.frameAndSend (/usr/lib/node_modules/cm-janus/node_modules/ws/lib/Sender.js:232:22)
at /usr/lib/node_modules/cm-janus/node_modules/ws/lib/Sender.js:126:12
at /usr/lib/node_modules/cm-janus/node_modules/ws/lib/PerMessageDeflate.js:313:5
at afterWrite (_stream_writable.js:354:3)
at onwrite (_stream_writable.js:345:7)
at WritableState.onwrite …
```

Loggly Alert: cm-janus fatal

---

lib/cm-api-client.js
lib/http-server.js
package.json

- intercept context-data sent from CM application (similar to websocket)
- change level from `debug` to `info` (https://github.com/cargomedia/cm-janus/blob/ceef69f6ff34e1db4077567a29e3acabd1676fe9/lib/http-server.js#L47)

Improve http server requests' logging

---

lib/janus/plugin/audio.js
lib/janus/plugin/video.js
test/spec/janus/plugin/audio.js
test/spec/janus/plugin/video.js

The websocket connection is closed by cm janus when a `list` request is received:
cm-janus log
```
{"time":"2016-05-26T10:47:54.386Z","level":"info","message":"Added connection","janus":{"connectionId":"31fa2e1e-caeb-4605-a994-c2739afb720d"}}
{"time":"2016-05-26T10:47:54.536Z","level":"info","message":"Added session","janus":{"sessionId":227270996,"connectionId":"31fa2e1e-caeb-4605-a994-c2739afb720d"}}
{"time":"2016-05-26T10:47:54.689Z","level":"info","message":"Added plugin","janus":{"pluginId":703128171,"sessionId":227270996,"connectionId":"31fa2e1e-caeb-4605-a994-c2739afb720d"}}
{"time":"2016-05-26T10:47:54.793Z","level":"error","message":"Unexpected proxy error. Closing proxy connection.","exception":{"janus":"message","body":{"request":"list"},"transaction":"j8DYZWS7GclL","token":"{\" …
```

"list" request doesn't work

---

lib/job/model/abstract.js
package.json

For alerting it would be nice if we could include the number of retries a job was tried in the log entry "Failed job process".
@vogdb wdyt, can it be easily added?
cc @kris-lab @tomaszdurka

Include "retryCount" in job processing error

---

lib/job/model/abstract.js

Added in: https://github.com/cargomedia/cm-janus/pull/264
I would suggest to move this field away from the root level of log entries. Compare [guidelines](https://github.com/cargomedia/guides/tree/master/logging).
I'm thinking either `jobData.retryCount` or `exception.retryCount`. I would go with the second.
@tomaszdurka @vogdb wdyt?

Move "retryCount" away from root level

---

bin/config.yaml

After https://github.com/cargomedia/cm/pull/2213 the site ID is not anymore part of the RPC endpoint.
Can you remove it from the docu and configuration?
Old:
```
http://www.cm.dev/rpc/null
```
New:
```
http://www.cm.dev/rpc
```

CM RPC API: remove site id

---

lib/channel.js
lib/janus/plugin/video.js
lib/streams.js
package.json
test/helpers/globals.js
test/spec/janus/plugin/video.js
test/unit/streams.js

Goal: make sure that all "subscribes" are removed against CM's API *before* sending the "unpublish" call. This way we can avoid streamchannels with only subscribes that appear briefly after an unsubscribe.
Would it make sense to send "unsubscribe" for all subscribers in `PluginVideo.removeStream()`, if the publish stream is removed?
We could also remove the whole plugin then…
Note: the plugin is in a unusable state after unpublish anyway, because any attempts to republish will fail, because CM will find that this "mediaId" already existed.
@tomaszdurka @vogdb wdyt?

Remove all "subscribe" streams when a rtpbroadcast "publish" stream is removed

---

lib/context.js
package.json

Reason:
Seems that our `var deepExtend = require('util')._extend;` doesn't work as expected.
https://github.com/cargomedia/cm-janus/blob/master/lib/context.js#L2
Did experiment:
```
tomasz@panda:~$ node
> var deepExtend = require('util')._extend;
undefined
> var hash = {janus: {jobId: 1}};
undefined
> deepExtend(hash, {janus: {jobData: {foo: 'bar'}}});
{ janus: { jobData: { foo: 'bar' } } }
> console.log(hash);
{ janus: { jobData: { foo: 'bar' } } }
undefined
```
Maybe let's go back to `deepExtend` after all?

AbstractJob context.janus is overwritten by child classes

---

lib/job/model/abstract.js
lib/job/processor.js
package.json

just to be sure, we log every time, but we add stdout/stdeer every Xth time? or we log nothing or everything every Xth time?
I would log nothing and everything every Xth time

Do not send stdout/stderr on failedRepeatedly exceptions

---

lib/job/model/abstract.js
package.json

As discussed with Tomasz:
- Log all incidents as errors
- Add `failedRepeatedly` at/after 10th incident
- Remove command output at/after 20th incident

Adjust command failure logging

---

lib/channel.js
lib/janus/proxy.js
lib/stream.js
package.json

Hi there,
This week a new version of the [uuid](https://github.com/kelektiv/node-uuid) module got released. The old module which was available by the name [node-uuid](https://www.npmjs.com/package/node-uuid) got deprecated and will show error message upon every install of the module.
To get rid of those install errors I've created this **automated pull request**. I've run some checks against your code base to test whether you're using one of the [deprecated apis](https://github.com/kelektiv/node-uuid/commit/5ae7287fc935eb55ef39133e4be17ef623ca000e), but this isn't the case.
Please test the changes against your code. I didn't run any tests and therefore can't guarantee that it isn't breaking. You can also just close this pr if you don't want to update your module.
In case there's already …

Update uuid to version 3.0.0

---

Vagrantfile
lib/job/file-listener.js
package.json
test/spec/job/file-listener.js

Until plugin version `0.0.28` of https://github.com/cargomedia/janus-gateway-rtpbroadcast the JobFile was created within final jobs folder (e.g. `/tmp/jobs`). `cm-janus` was listening for changes and pick-up new coming jobs/files.
Since plugin `0.0.29-beta` the job files are not created directly into final job folder (subscribed by cm-janus), but rather created in temporary job folder (e.g. `/tmp/jobs-temp`) and moved to final job folder (e.g. `/tmp/jobs`) after the task is finished.
This was introduced beacuse of https://github.com/cargomedia/janus-gateway-rtpbroadcast/pull/107
@tomaszdurka wdyt?
cc @njam

Not detected "job" files when moved to the folder
